# Generated by Django 5.2 on 2025-10-19 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gmail', models.EmailField(max_length=254)),
                ('uucms_num', models.CharField(max_length=15)),
                ('rno', models.IntegerField()),
                ('photo', models.ImageField(null=True, upload_to='studentphoto/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.courses')),
            ],
        ),
    ]
