# Generated by Django 5.2 on 2025-10-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canaradatabase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gmail',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
