# Generated by Django 5.2 on 2025-10-19 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canaradatabase', '0002_alter_student_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='course',
            new_name='course_name',
        ),
    ]
