# Generated by Django 5.2 on 2025-10-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gmail',
            field=models.EmailField(blank=True, default='chandu@gmail.com', max_length=254, null=True),
        ),
    ]
