# Generated by Django 5.2 on 2025-11-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_profile_gmail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
