# Generated by Django 5.2 on 2025-10-19 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Course', '0002_rename_name_courses_course_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Teacher Name')),
                ('qualification', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('subjects', models.CharField(blank=True, max_length=200, null=True)),
                ('experience', models.PositiveIntegerField(help_text='Experience in years')),
                ('about', models.TextField(blank=True, max_length=500, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='Course.courses')),
            ],
        ),
    ]
