# Generated by Django 5.2 on 2025-10-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='t_image',
            field=models.ImageField(blank=True, null=True, upload_to='teacher'),
        ),
    ]
